# Generated by Django 5.2.7 on 2025-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_imagenes/', verbose_name='Foto de Perfil'),
        ),
    ]
