# Generated by Django 5.2.7 on 2025-12-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketplace_App', '0002_perfilusuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
